---
name: BIOPYPIR-APPROVED
on: [push,pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [2.7] #,3.5,3.6,3.7] 
        os: [macOS-latest, ubuntu-latest] 
    steps:
    - name: STEP 1. Check-Out Repo 
      uses: actions/checkout@v2     
    #===============================================#
    - name: STEP 2. Set-Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: custom linter
      uses: benstear/python-pylint-github-action@master
      id: linter
      with:
        package_name: scikit-rebate
        verbosity: score_only
        
    #===============================================#
    - name: STEP 3. Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        
        pip install numpy
        pip install scipy
        pip install pandas
        pip install sklearn
        pip install nose
        
        pip install .
        pip install pytest
        pip install python-coveralls
        pip install coveralls
        pip install junit2html
        
    - name: simple pytest
      run: nosetests -s -v 
      # python setup.py test

    - name: STEP 7. Zip Artifacts
      run: |
        zip artifacts.zip coverage-report.html coverage-report-2.html pylint-report.txt
    #${{ steps.linter.outputs.linting-report }}
    #===============================================#
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts.zip
        path: artifacts.zip
